# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StackitServer < Formula
  desc "Server for stackit web UI and API"
  homepage "https://github.com/getstackit/stackit"
  version "0.18.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/getstackit/stackit/releases/download/v0.18.1/stackit-server_Darwin_x86_64.tar.gz"
      sha256 "449bae62fb5ecf46e2f50831f0267a3ccb4f4e3c92df3a0b8400a685de999785"

      define_method(:install) do
        bin.install "stackit-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/getstackit/stackit/releases/download/v0.18.1/stackit-server_Darwin_arm64.tar.gz"
      sha256 "df6b3c58dc7d138595a16301775631b4444583b9e77eab42c9dbe2e68efd19a2"

      define_method(:install) do
        bin.install "stackit-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/getstackit/stackit/releases/download/v0.18.1/stackit-server_Linux_x86_64.tar.gz"
      sha256 "980c8fa9f30457371a70b20a6ad7089f86abd52d9e61818b520cbe999787e067"
      define_method(:install) do
        bin.install "stackit-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/getstackit/stackit/releases/download/v0.18.1/stackit-server_Linux_arm64.tar.gz"
      sha256 "84ff324fd2efffee350f8f8a4356fbb4d774b37c6b9b88fc174619746bf0c45b"
      define_method(:install) do
        bin.install "stackit-server"
      end
    end
  end

  test do
    system "#{bin}/stackit-server", "--help"
  end
end
