# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stackit < Formula
  desc "Command-line tool for managing stacked changes in Git"
  homepage "https://github.com/getstackit/stackit"
  version "0.15.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/getstackit/stackit/releases/download/v0.15.1/stackit_Darwin_x86_64.tar.gz"
      sha256 "fdf624c974149d1a7149330aa40e1924491ae246813aeb6c85ac17280a377ba8"

      def install
        bin.install "stackit"
        bin.install_symlink "stackit" => "st"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/getstackit/stackit/releases/download/v0.15.1/stackit_Darwin_arm64.tar.gz"
      sha256 "d78ca64d03656be8b5ebd471bdc19d91c9237eb086f41e08751e474c74971f41"

      def install
        bin.install "stackit"
        bin.install_symlink "stackit" => "st"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/getstackit/stackit/releases/download/v0.15.1/stackit_Linux_x86_64.tar.gz"
      sha256 "c0b7d0c230c22f5388bb8ec27fcc2ab144a48c0ed507ab68d27bf84deaeab38a"
      def install
        bin.install "stackit"
        bin.install_symlink "stackit" => "st"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/getstackit/stackit/releases/download/v0.15.1/stackit_Linux_arm64.tar.gz"
      sha256 "51f0c363a513833b34dcdfe16bfd166b3948127cbb97b0d4b2a71901ae55fafe"
      def install
        bin.install "stackit"
        bin.install_symlink "stackit" => "st"
      end
    end
  end

  test do
    system "#{bin}/stackit", "--version"
  end
end
