# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stackit < Formula
  desc "Command-line tool for managing stacked changes in Git"
  homepage "https://github.com/getstackit/stackit"
  version "0.15.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/getstackit/stackit/releases/download/v0.15.4/stackit_Darwin_x86_64.tar.gz"
      sha256 "b04a9d89034783c1c13adc283243065fe211db907e2234fb354ae5739971df2f"

      def install
        bin.install "stackit"
        bin.install_symlink "stackit" => "st"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/getstackit/stackit/releases/download/v0.15.4/stackit_Darwin_arm64.tar.gz"
      sha256 "9ef6c0d5540d191320586c6e27413475a022f7d20ff2881ae5bd9bd82be9f773"

      def install
        bin.install "stackit"
        bin.install_symlink "stackit" => "st"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/getstackit/stackit/releases/download/v0.15.4/stackit_Linux_x86_64.tar.gz"
      sha256 "395291a73f2cdd63181d6e74a6ba9d6602170170e87bf47a5f1c712cc6c15fe3"
      def install
        bin.install "stackit"
        bin.install_symlink "stackit" => "st"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/getstackit/stackit/releases/download/v0.15.4/stackit_Linux_arm64.tar.gz"
      sha256 "d5b6ce6ee4b52c485a3aea3a4b67857c35e9aa83c11b92ec7190a9543b2295b1"
      def install
        bin.install "stackit"
        bin.install_symlink "stackit" => "st"
      end
    end
  end

  test do
    system "#{bin}/stackit", "--version"
  end
end
